### ISSUE TITLE
Compilation issue: Missing strtod_l and locale_t

### ISSUE THREAD

**Issue by AlbertoEAF** [lemire/fast_double_parser#30] opened 2020-09-25 16:30 UTC
Hello,

I'm using this library for LightGBM (microsoft/LightGBM#3405) and whilst I'm really happy with it, there are some CI environments where this does not compile. I don't understand why. CMakeLists claims strtod_l was found:
```
-- Looking for strtod_l - found
-- Configuring done
```

You can see the job error details here. See lines 704 and 708 for instance: https://travis-ci.org/github/microsoft/LightGBM/jobs/730024056
![image](https://user-images.githubusercontent.com/3976753/94292191-857b2f80-ff54-11ea-8733-9b146812699b.png)

I first mistakenly added this issue at the fmt library which I'm also using and they suggested using this https://github.com/fmtlib/fmt/issues/1901.

As `strtod_l` and `locale_t` are non-standard, how do you solve this usually?

**Comment by lemire** [comment] 2020-09-25 16:47
Thanks for the report. It looks like it might be a bug on my end.

> As strtod_l and locale_t are non-standard, how do you solve this usually?

You are using GNU GCC and it definitively supports it.

It even says so in your stream...
```
-- Looking for strtod_l
-- Looking for strtod_l - found
```

**Comment by lemire** [comment] 2020-09-25 16:49
Let me investigate the issue a bit.

**Comment by lemire** [comment] 2020-09-25 16:52
I think I understand what is going on.

**Comment by lemire** [comment] 2020-09-25 17:14
@AlbertoEAF Can you try with this commit... 
https://github.com/lemire/fast_double_parser/commit/e09e5aad828bcb16bea7ed0ed8322e019112fdbe

My guess is not that you are missing the function but rather that, somehow, the include xlocale.h does not pan out. It is a complicated issue. If you are mixing and matching various runtime libraries and with various compilers, it gets a bit tricky.

I think my new heuristic should work.

(I looked at your CI and it a bit difficult to reproduce at the moment.)

**Comment by AlbertoEAF** [comment] 2020-09-25 21:26
Great Lemire! I will test it Monday ;)

**Comment by lemire** [comment] 2020-09-25 21:52
@AlbertoEAF Great. Please follow-up. This include code is something new, and I am eager to get it right.

**Comment by lemire** [comment] 2020-09-27 02:20
It is really simply a matter of declaring the function which may involve including the right header. My backup plan is to kill strtod_l and go with @nigeltao proposal (which is to include our own fallback parser... thankfully something that is quite easy thanks to Nigel's pointers). It will fatten a bit the header, so I'd prefer if we could just use strtod_l especially since it is present on the systems you care about.

**Comment by AlbertoEAF** [comment] 2020-09-28 09:56
By the way, the other library I'm using follows this approach:
https://github.com/fmtlib/fmt/blob/6cccdc24bcb8605965c1e2497c61504cd388bde9/include/fmt/os.h#L16-L24

Don't know if it helps, anyway I'll try your commit first ;)

**Comment by lemire** [comment] 2020-09-28 13:49
@AlbertoEAF 

On freebsd and apple platforms, we definitively should be including xlocale.h already.

This morning, I will see about adding more platform coverage on my end.

**Comment by lemire** [comment] 2020-09-28 16:12
@AlbertoEAF I have just updated my CI to include many, many systems... Visit the README on github...

https://github.com/lemire/fast_double_parser

I cannot reproduce any build problems.

Did you get around to testing the issue further? E.g., you could just describe the system where you encounter the issue.

**Comment by lemire** [comment] 2020-09-28 16:16
Note that my CI tests include FreeBSD. They do not include macos but I am a mac user myself, so mac support is never an issue.

**Comment by AlbertoEAF** [comment] 2020-09-29 17:37
Hello @lemire, yes we had progress using that commit. ;)

It no longer fails on that job due to locale: https://travis-ci.org/github/microsoft/LightGBM/jobs/731344749.

Now it fails with internal LGBM build system issues alone, of not including the new libs somehow. I have to get help from them as I don't know why.

I'd like to thank you for your work @lemire, it was a really quick turn-around time and effective ;)

Thanks for developing and maintaining this project!

**Comment by lemire** [comment] 2020-09-29 21:21
Fantastic. I am closing this issue now. Please come back if there is more we can do.

**Closed by lemire** 2020-09-29 21:21 UTC
